import type { IWarehouse } from "./Warehouse";

export interface Customers {
  id: number;
  name: string;
  warehouseId: number;
  discountClassId: number | null;
  taxId: string;
  salespersonId: number | null;
  locked: boolean;
  creditAlert: null | string;
  paymentTerms: number | null;
  status: boolean;
  shipViaId: number | null;
  source: string;
  website: string;
  emailStatements: boolean;
  emailInvoices: boolean;
  creditLimit: number | null;
  financeCharges: boolean;
  defaultTerms: number | null;
  shipSun: boolean;
  shipMon: boolean;
  shipTues: boolean;
  shipWed: boolean;
  shipThurs: boolean;
  shipFri: boolean;
  shipSat: boolean;
  customerNumber: string;
  mapCode: string;
  internalSale: boolean;
  categoryId: number | null;
  billingAddress: string;
  billingAddress2: string;
  billingCity: string;
  billingState: string;
  billingZip: string;
  generalNotes: string;
  shippingNotes: string;
  productionNotes: string;
  corporateAccountId: number | null;
  routeOrder: number | null;
  taxable: boolean;
  printStatement: boolean;
  arNotes: string;
  customerTypeId: number | null;
  isCreditHold: boolean;
  isDeleted: boolean;
  isDefault: boolean;
  mailInvoices: boolean;
  customerGroupId: number | null;
  createdDate: Date | null;
  createdUserid: number | null;
  customerGroup: number | null;
  customerShippingAddresses: any[];
  customersContacts: any[];
  webOrder: any[];
  workOrders: any[];
  payments: any[];
  openInvoices: number;
  openCredits: number;
  currentBalance: number;
  warehouse: IWarehouse;
}
