import type { WebOrder } from "./WebOrder";
import type { WorkOrderDetails } from "./WorkOrderDetails";

export interface WorkOrder {
  id: number;
  created: Date;
  modified: Date;
  warehouseId: number;
  customerId: number;
  termsId: number | null;
  shippingAddressId: number | null;
  shipToContact: string | null;
  shipToAddress: string | null;
  shipToAddress2: string | null;
  contactName: string | null;
  contactPhone: string | null;
  contactFax: string | null;
  salesmanId: number | null;
  shipviaId: number | null;
  poNumber: string | null;
  requiredDate: Date | null;
  workOrderComment: string | null;
  invoiceComment: string | null;
  status: string;
  approvedDate: Date | null;
  approvedUserid: number | null;
  pickedDate: Date | null;
  pickedUserid: number | null;
  shippingAmount: number | null;
  confirmedDate: Date | null;
  confirmedUserid: number | null;
  salesTaxRate: number | null;
  salesTaxAmount: number | null;
  shipToAddress3: string | null;
  shipToCity: string | null;
  shipToState: string | null;
  shipToZip: string | null;
  totalAmount: number;
  balance: number | null;
  printedDate: Date | null;
  dueDate: Date | null;
  invoiceDate: Date | null;
  orderDate: Date;
  routeId: number | null;
  shipToName: string | null;
  subTotal: number | null;
  oldInvoiceId: number | null;
  createdUserid: number | null;
  driverId: number | null;
  collectPayment: boolean;
  invoiceMessage: string | null;
  invoiceMessageId: number | null;
  orderType: string;
  shipToCustomerNumber: string | null;
  shipToContactName: string;
  shipToContactPhone: string | null;
  shipToContactFax: string | null;
  taxable: boolean;
  manualDiscountPercent: number | null;
  manualDiscountAmount: null;
  stateTaxRate: number | null;
  countyTaxRate: number | null;
  cityTaxRate: number | null;
  stateTaxAmount: number | null;
  countyTaxAmount: number | null;
  cityTaxAmount: number | null;
  oldInvoiceNumber: string | null;
  internalSale: boolean;
  oldStatus: string | null;
  orderUserid: number | null;
  deletedUserid: number | null;
  deletedDate: Date | null;
  source: string;
  version: string;
  trackingNumber: string | null;
  customers: null;
  salesman: null;
  warehouses: null;
  inventoryItemTransactions: any[];
  workOrderDetails: WorkOrderDetails[];
  webOrder: WebOrder[];
}
